label2id = {
    "B-DATETIME": 0,
    "I-DATETIME": 1,
    "O": 2,
    "B-ROLE": 3,
    "B-ORGANIZATION": 4,
    "I-ROLE": 5,
    "B-PERSON": 6,
    "I-PERSON": 7,
    "B-LOCATION": 8,
    "I-LOCATION": 9,
    "B-DEPARTMENT": 10,
    "I-ORGANIZATION": 11,
    "I-DEPARTMENT": 12,
}
id2label = {
    0:"B-DATETIME",
    1:"I-DATETIME",
    2:"O",
    3:"B-ROLE",
    4:"B-ORGANIZATION",
    5:"I-ROLE",
    6:"B-PERSON",
    7:"I-PERSON",
    8:"B-LOCATION",
    9:"I-LOCATION",
    10:"B-DEPARTMENT",
    11:"I-ORGANIZATION",
    12:"I-DEPARTMENT",
}